server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

  config:
    import: configserver:http://localhost:8085

#  profiles:
#    active: prod

#  eureka:
#    instance:
#      hostname: localhost
#      preferIpAddress: true
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka/

# OKTA configuration for API Gateway

okta:
  oauth2:
    issuer: https://dev-48528771.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa804xf9j3AiZcNy5d7
    client-secret: VtGJ86zTHWAXTSlEUtvMLnYOIwUQjOQn_l7QQFYj
    scopes: openid, profile, email, offline_access